import createFetchClient from 'openapi-fetch';
import createClient from 'openapi-react-query';

import type { paths } from './openapi-spec'; // generated by openapi-typescript

export const API_BASE_URL = import.meta.env.PUBLIC_API_BASE_URL || '';

export const fetchClient = createFetchClient<paths>({ baseUrl: API_BASE_URL });

export const $api = createClient(fetchClient);
